local _, ---@class ns
ns = ...

---@class ns.constants
ns.constants = {
  playStyleString = {
    [1] = "",
    [2] = "Compl",
    [3] = "Time",
  },
  friendlyName = "LFMP",
  ratingMin = 0,
  ratingMax = 3500,
  atlas = {
    DAMAGER = "groupfinder-icon-role-large-dps",
    TANK = "groupfinder-icon-role-large-tank",
    HEALER = "groupfinder-icon-role-large-healer",
    NA = "communities-icon-redx"
  },
  declineQueueMax = 15,
  lengths = { name = "%-12s", server = "%-15s", score = "%-4s" },
  dungeons = {
    ["PF"] = { cmID = 379, aID = 691 },
    ["DOS"] = { cmID = 377, aID = 695 },
    ["HOA"] = { cmID = 378, aID = 699 },
    ["MISTS"] = { cmID = 375, aID = 703 },
    ["SD"] = { cmID = 380, aID = 705 },
    ["SOA"] = { cmID = 381, aID = 709 },
    ["NW"] = { cmID = 376, aID = 713 },
    ["TOP"] = { cmID = 382, aID = 717 },
    ["STRT"] = { cmID = 391, aID = 1016 },
    ["GMBT"] = { cmID = 392, aID = 1017 },
    ["WKSHP"] = { cmID = 370, aID = 683 },
    ["DOCK"] = { cmID = 169, aID = 180 },
    ["GRIM"] = { cmID = 166, aID = 183 },
    ["LOWR"] = { cmID = 227, aID = 473 },
    ["JUNK"] = { cmID = 369, aID = 679 },
    ["UPPR"] = { cmID = 234, aID = 471 },
  },
  timewalk = {
    [459] = { shortName = "EOA" },
    [460] = { shortName = "DHT" },
    [462] = { shortName = "NL" },
    [464] = { shortName = "VOTW" },
    [463] = { shortName = "BRH" },
    [466] = { shortName = "COS" },
  },
  mapInfo = {
    [379] = { shortName = "PF", activityId = 691 },
    [377] = { shortName = "DOS", activityId = 695 },
    [378] = { shortName = "HOA", activityId = 699 },
    [375] = { shortName = "MISTS", activityId = 703 },
    [380] = { shortName = "SD", activityId = 705 },
    [381] = { shortName = "SOA", activityId = 709 },
    [376] = { shortName = "NW", activityId = 713 },
    [382] = { shortName = "TOP", activityId = 717 },
    [391] = { shortName = "STRT", activityId = 1016 },
    [392] = { shortName = "GMBT", activityId = 1017 },
    [370] = { shortName = "WKSHP", activityId = 683 },
    [169] = { shortName = "DOCK", activityId = 180 },
    [166] = { shortName = "GRIM", activityId = 183 },
    [227] = { shortName = "LOWR", activityId = 471 },
    [369] = { shortName = "JUNK", activityId = 679 },
    [234] = { shortName = "UPPR", activityId = 473 },
  },
  trackedEvents = {
    ["LFG_LIST_AVAILABILITY_UPDATE"] = false,
    ["LFG_LIST_ACTIVE_ENTRY_UPDATE"] = true,
    ["LFG_LIST_ENTRY_CREATION_FAILED"] = false,
    ["LFG_LIST_SEARCH_RESULTS_RECEIVED"] = true,
    ["LFG_LIST_SEARCH_RESULT_UPDATED"] = true,
    ["LFG_LIST_SEARCH_FAILED"] = false,
    ["LFG_LIST_APPLICANT_LIST_UPDATED"] = false,
    ["LFG_LIST_APPLICANT_UPDATED"] = true,
    ["LFG_LIST_ENTRY_EXPIRED_TOO_MANY_PLAYERS"] = false,
    ["LFG_LIST_ENTRY_EXPIRED_TIMEOUT"] = false,
    ["LFG_LIST_APPLICATION_STATUS_UPDATED"] = false,
    ["LFG_GROUP_DELISTED_LEADERSHIP_CHANGE"] = false,
    ["PLAYER_SPECIALIZATION_CHANGED"] = true,
    ["PARTY_LEADER_CHANGED"] = true,
    ["GROUP_ROSTER_UPDATE"] = true
  },
  searchEntryFrames = { "classDot", "roleIcon", "classBar" },
  ---@class ns.constants.defaults
  defaults = {
    global = {
      -- Control Panel Defaults
      enabled = true,
      showLeaderScore = true,
      showRealmName = true,
      shortenActivityName = true,
      alwaysShowFriends = true,
      lfgListingDoubleClick = true,
      signupOnEnter = false,
      autoFocusSignUp = false,
      alwaysShowRoles = false,
      hideAppViewerOverlay = false,
      enableLFGDropdown = true,
      excludePlayerList = true,
      flagPlayer = false,
      filterPlayer = false,
      flagPlayerList = {},
      excludeRealmList = true,
      flagRealm = false,
      filterRealm = false,
      flagRealmList = {},
      activeRoleFilter = false,
      classFilter = false,
      -- UI Defaults
      ratingFilter = false,
      ratingFilterMin = 0,
      ratingFilterMax = 0,
      dungeonFilter = false,
      realmList = {},
      classRoleDisplay = "def",
      showPartyLeader = false,
      dungeonAbbr = {
        [691] = "PF",
        [695] = "DOS",
        [699] = "HOA",
        [703] = "MOTS",
        [705] = "SD",
        [709] = "SOA",
        [713] = "NW",
        [717] = "TOP",
        [1016] = "STRT",
        [1017] = "GMBT"
      }
    }
  },
}

ns.constants.actvityInfo = {
  [691] = ns.constants.mapInfo[379],
  [695] = ns.constants.mapInfo[377],
  [699] = ns.constants.mapInfo[378],
  [703] = ns.constants.mapInfo[375],
  [705] = ns.constants.mapInfo[380],
  [709] = ns.constants.mapInfo[381],
  [713] = ns.constants.mapInfo[376],
  [717] = ns.constants.mapInfo[382],
  [1016] = ns.constants.mapInfo[391],
  [1017] = ns.constants.mapInfo[392],
  [459] = ns.constants.timewalk[459],
  [460] = ns.constants.timewalk[460],
  [462] = ns.constants.timewalk[462],
  [464] = ns.constants.timewalk[464],
  [463] = ns.constants.timewalk[463],
  [466] = ns.constants.timewalk[466],
  [683] = ns.constants.mapInfo[370],
  [180] = ns.constants.mapInfo[169],
  [183] = ns.constants.mapInfo[166],
  [471] = ns.constants.mapInfo[227],
  [679] = ns.constants.mapInfo[369],
  [473] = ns.constants.mapInfo[234],
}
